#!/bin/bash

build_with_meson() {
	echo "Building in ${PWD}..."
	meson compile -C .build
	exit ${?}
}

build_with_python() {
	echo "Building in ${PWD}..."
	python3 -m build --wheel
	exit ${?}
}

makefile() {
	echo "Building in ${PWD}..."
	make Debug
	exit ${?}
}

if [ "${1}" == "" ]; then
	MODE="auto"
else
	MODE="${1}"
fi

while [ ${PWD} != '/' ]
do

	if [ "${MODE}" == "auto" ]; then

		if [ -e pyproject.toml ]; then
			build_with_python

		elif [ -e meson.build ]; then
			build_with_meson

		elif [ -e Makefile ]; then
			makefile
		fi

	elif [ ${MODE} == 'meson' ]; then
		if [ -e meson.build ]; then
			meson
		fi

	elif [ ${MODE} == 'make' ]; then
		if [ -e Makefile ]; then
			makefile
		fi

	elif [ ${MODE} == 'flatpak' ]; then

		YML_FILE=$(find flathub -name '*.yml' | head -1)
		rm -fr ./.flatpak
		
		if [ -d ./flatpak ]; then
			flatpak-builder --disable-cache --force-clean --install --user ./.flatpak $(find flathub -name '*.yml' | head -1)
			rc=${?}
		elif [ -d ./flathub ]; then
			echo "Building Flatpak using manifest: ${YML_FILE}"
			flatpak-builder --disable-cache --force-clean --install --user ./.flatpak ${YML_FILE}
			rc=${?}
		fi

		if [ ${rc} -ne 0 ]; then
			echo "Flatpak build failed"
			exit ${rc}
		fi

		exit 0
	fi

	cd ..

done

echo "Unable to identify build system"
exit 1
