#!/bin/bash

if [ -e meson.build ]; then
	meson compile -C .build
	exit ${?}
fi

if [ -e .build/build.ninja ]; then
	ninja -C .build
	exit ${?}
fi

if [ -e Makefile ]; then
	make Debug
	exit ${?}
fi


